apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplikacja1
  namespace: aplikacja
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 2
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: dockersamples/static-site
        env:
        - name: Dominik
          value: app1
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplikacja2
  namespace: aplikacja
spec:
  selector:
    matchLabels:
      app: app2
  replicas: 2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: httpd
        env:
        - name: Dominik
          value: app2
        ports:
        - containerPort: 80

