apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller-conf
  namespace: ingress
  labels:
    app: nginx-ingress-lb
data:
  proxy-request-buffering: "off"
  proxy-buffering: "off"
  enable-vts-status: "on"
