kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-reader-binding
  namespace: aplikacja
subjects:
- kind: User
  name: hal9000
  apiGroup: ""
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: ""
