kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: aplikacja
  name: pod-reader
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
